services:
  api:
    build: .
    container_name: sys-api
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - redis
    restart: always

  redis:
    image: redis:7-alpine
    container_name: sys-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: always
    command: redis-server --appendonly yes

volumes:
  redis_data:
